#!/usr/bin/env node
/**
 * On-demand full-project snapshot → `.context-snapshot.md` (gitignored).
 *
 * STACK-AGNOSTIC. Produces a single document useful for:
 *   - A brutal refactor where Claude needs to see the whole tree at once.
 *   - Pasting into another AI (ChatGPT, Gemini) that lacks the boot hook.
 *   - Impact analysis ("what breaks if I change X?").
 *
 * Contents: folder tree (depth-limited), detected stack, latest session,
 * CHANGELOG `[Unreleased]`, and a glossary excerpt. Best-effort, never throws.
 *
 * Usage:  node vibekit/tools/scripts/generate-context.mjs
 */
import { readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const ROOT = process.cwd();
const OUTPUT = resolve(ROOT, '.context-snapshot.md');
const MAX_DEPTH = 4;
const IGNORE = new Set(['node_modules', '.git', 'dist', 'build', 'out', '.next', '.turbo', '.expo', 'coverage', '__pycache__', 'target', 'vendor', '.claude']);

async function readSafe(rel) {
  try {
    return await readFile(resolve(ROOT, rel), 'utf-8');
  } catch {
    return null;
  }
}

async function buildTree(dir, prefix = '', depth = 0) {
  if (depth > MAX_DEPTH) return [];
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return [];
  }
  entries = entries.filter((e) => !(e.isDirectory() && IGNORE.has(e.name)) && !e.name.startsWith('.tmp'));
  entries.sort((a, b) => (a.isDirectory() === b.isDirectory() ? a.name.localeCompare(b.name) : a.isDirectory() ? -1 : 1));
  const lines = [];
  for (const e of entries.slice(0, 60)) {
    lines.push(`${prefix}${e.isDirectory() ? '📁' : '📄'} ${e.name}`);
    if (e.isDirectory()) lines.push(...(await buildTree(resolve(dir, e.name), prefix + '  ', depth + 1)));
  }
  return lines;
}

async function detectStack() {
  const hints = [];
  const pkgRaw = await readSafe('package.json');
  if (pkgRaw) {
    try {
      const pkg = JSON.parse(pkgRaw);
      const deps = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) };
      hints.push(`**package.json** — ${Object.keys(deps).length} deps. Key: ${Object.keys(deps).slice(0, 15).join(', ')}`);
    } catch {
      /* ignore */
    }
  }
  for (const [file, label] of [
    ['pyproject.toml', 'Python (pyproject.toml)'],
    ['go.mod', 'Go (go.mod)'],
    ['Cargo.toml', 'Rust (Cargo.toml)'],
    ['pom.xml', 'Java (Maven)'],
    ['Gemfile', 'Ruby (Gemfile)'],
  ]) {
    if (await readSafe(file)) hints.push(`**${label}**`);
  }
  return hints.length ? hints.map((h) => `- ${h}`).join('\n') : '_(no recognized manifest)_';
}

async function latestSession() {
  let files = [];
  try {
    files = await readdir(resolve(ROOT, 'vibekit/memory/sessions'));
  } catch {
    return null;
  }
  const entries = files.filter((f) => /^\d{4}-\d{2}-\d{2}-\d{2,}-.+\.md$/.test(f)).sort((a, b) => Number.parseInt(b.split('-')[3], 10) - Number.parseInt(a.split('-')[3], 10));
  if (!entries.length) return null;
  const content = await readSafe(`vibekit/memory/sessions/${entries[0]}`);
  return content ? content.split('\n').slice(0, 40).join('\n') : null;
}

function unreleased(changelog) {
  if (!changelog) return null;
  const lines = changelog.split('\n');
  const start = lines.findIndex((l) => /^##\s+\[Unreleased\]/i.test(l));
  if (start === -1) return null;
  const rest = lines.slice(start + 1);
  const end = rest.findIndex((l) => /^##\s+\[/.test(l) || l.trim() === '---');
  return rest.slice(0, end === -1 ? 40 : end).join('\n').trim();
}

async function main() {
  const out = [];
  out.push(`# Context Snapshot — ${new Date().toISOString().slice(0, 10)}`);
  out.push('');
  out.push('> Generated by `generate-context`. Gitignored, ephemeral. Do not commit.');
  out.push('');
  out.push('## Detected stack');
  out.push('');
  out.push(await detectStack());
  out.push('');
  out.push('## Project tree (depth ≤ 4)');
  out.push('');
  out.push('```');
  out.push(...(await buildTree(ROOT)));
  out.push('```');
  out.push('');
  const session = await latestSession();
  if (session) {
    out.push('## Latest session');
    out.push('');
    out.push(session);
    out.push('');
  }
  const unrel = unreleased(await readSafe('docs/CHANGELOG.md'));
  if (unrel) {
    out.push('## CHANGELOG [Unreleased]');
    out.push('');
    out.push(unrel);
    out.push('');
  }
  const glossary = await readSafe('vibekit/memory/GLOSSARY.md');
  if (glossary) {
    out.push('## Glossary (excerpt)');
    out.push('');
    out.push(glossary.split('\n').slice(0, 40).join('\n'));
    out.push('');
  }
  await writeFile(OUTPUT, out.join('\n'), 'utf-8');
  console.log(`✅ .context-snapshot.md regenerated (${out.length} lines).`);
}

main().catch((err) => {
  console.error('❌ Failed to generate context snapshot:', err);
  process.exit(1);
});
