/**
 * DevPipeline board rendering — turns the task list into `devpipeline.md`.
 *
 * Pure (takes the task array), so `pipeline.mjs` (the CLI) stays lean. Shows the
 * WSJF priority + SLA, and flags overdue items (⏰).
 */
import { isOverdue } from './pipeline-prioritize.mjs';

function table(tasks) {
  if (tasks.length === 0) return '_(empty)_\n';
  const rows = ['| ID | Pri | WSJF | Type | Title | SLA | Roadmap |', '| --- | --- | --- | --- | --- | --- | --- |'];
  for (const t of tasks) {
    const sla = t.sla ? (isOverdue(t) ? `⏰ ${t.sla}` : t.sla) : '—';
    rows.push(`| ${t.id} | ${t.priority} | ${t.wsjf || '—'} | ${t.type} | ${t.title} | ${sla} | ${t.roadmap || '—'} |`);
  }
  return rows.join('\n') + '\n';
}

/** Owner cell for the in-progress lane: 🟢 live / 🟡 idle session + branch. */
function ownerCell(task) {
  if (!task.owner) return '_unassigned_';
  const session = `\`${String(task.owner).slice(0, 8)}\``;
  const dot = task.active ? '🟢' : '🟡';
  const branch = task.branch ? ` · \`${task.branch}\`` : '';
  return `${dot} ${session}${branch}`;
}

/** In-progress lane — like `table` but with the owning session instead of WSJF/roadmap. */
function testingTable(tasks) {
  if (tasks.length === 0) return '_(empty — nothing pulled into testing. `/pipeline start <id>` to claim one.)_\n';
  const rows = ['| ID | Pri | Type | Title | Owner (session · branch) | SLA |', '| --- | --- | --- | --- | --- | --- |'];
  for (const t of tasks) {
    const sla = t.sla ? (isOverdue(t) ? `⏰ ${t.sla}` : t.sla) : '—';
    rows.push(`| ${t.id} | ${t.priority} | ${t.type} | ${t.title} | ${ownerCell(t)} | ${sla} |`);
  }
  return rows.join('\n') + '\n';
}

/** One-line git-policy note so any reader knows whether this board is shared or local-only. */
function gitPolicyNote(opts) {
  return opts.commitBoard === false
    ? 'this board is **local-only** (gitignored) — pure execution control, never published; only the task files (if any) travel.'
    : 'committed as **shared team state**. (A repo dogfooding the kit may exclude all of `vibekit/` locally, so its board never reaches the published kit.)';
}

/**
 * Full `devpipeline.md` markdown from the task list.
 *
 * @param {Array} tasks — task list (in-testing items may carry `owner`/`branch`/`active`).
 * @param {{ commitBoard?: boolean }} [opts] — git policy, surfaced in the header.
 */
export function renderBoard(tasks, opts = {}) {
  const by = (s) => tasks.filter((t) => t.stage === s);
  const overdue = tasks.filter(isOverdue);
  const out = [];
  out.push('# DevPipeline — execution board');
  out.push('');
  out.push('> ⚠️  **AUTO-GENERATED** by `pipeline.mjs sync` (also on pre-commit). Do not hand-edit.');
  out.push('> **What this is:** execution *control* — the live board of bugs / increments / chores');
  out.push('> with **WSJF** priority + **SLA** (⏰ = overdue). The product/business plan is a separate');
  out.push('> doc — `vibekit/memory/roadmap.md` (the what/why). This is the how/now.');
  out.push('> **In progress** shows the task **and the session working it** (🟢 = that session is live).');
  out.push(`> **Git:** ${gitPolicyNote(opts)}`);
  out.push('');
  out.push(`Backlog **${by('backlog').length}** · Testing **${by('testing').length}** · Concluded **${by('conclusion').length}** · ⏰ Overdue **${overdue.length}**`);
  out.push('');
  out.push('## 🟡 In testing / in progress');
  out.push('');
  out.push(testingTable(by('testing')));
  out.push('## 📋 Backlog (by priority)');
  out.push('');
  out.push(table(by('backlog')));
  out.push('## ✅ Concluded (recent)');
  out.push('');
  out.push(table(by('conclusion').slice(-15)));
  return out.join('\n');
}

const SEV_ORDER = ['S1', 'S2', 'S3', 'S4', ''];
const SEV_LABEL = { S1: 'S1 · Critical', S2: 'S2 · High', S3: 'S3 · Medium', S4: 'S4 · Low', '': 'Unclassified' };

/** Known-bugs map: every `type: bug` task, grouped by severity, open vs resolved. */
export function renderKnownBugs(tasks) {
  const bugs = tasks.filter((t) => t.type === 'bug');
  const out = ['# Known Bugs — map', ''];
  out.push('> ⚠️ AUTO-GENERATED by `pipeline.mjs sync`. The bug registry, grouped by severity.');
  out.push(`> ${bugs.length} known · ${bugs.filter((b) => b.stage !== 'conclusion').length} open · ${bugs.filter(isOverdue).length} ⏰ overdue`);
  out.push('');
  if (bugs.length === 0) return out.concat(['✅ No bugs on record.', '']).join('\n');
  for (const sev of SEV_ORDER) {
    const inSev = bugs.filter((b) => (b.severity || '') === sev);
    if (inSev.length === 0) continue;
    out.push(`## ${SEV_LABEL[sev]} (${inSev.length})`, '', '| ID | Status | Bug type | Title | SLA |', '| --- | --- | --- | --- | --- |');
    for (const b of inSev) {
      const status = b.stage === 'conclusion' ? '✅ resolved' : b.stage === 'testing' ? '🟡 testing' : '📋 open';
      const sla = b.sla ? (isOverdue(b) ? `⏰ ${b.sla}` : b.sla) : '—';
      out.push(`| ${b.id} | ${status} | ${b.bugType || '—'} | ${b.title} | ${sla} |`);
    }
    out.push('');
  }
  return out.join('\n');
}
