/**
 * prompt-engineer — render the canonical system prompt to per-provider variants.
 * Fase 1 ships Anthropic + OpenAI; Fases 2+ add Gemini, DeepSeek, Ollama via the
 * same section map. Pure + zero-dep — no LLM call at this layer.
 *
 * Canonical sections (the single source of truth) live in `prompts/system.canonical.md`:
 *   `# Role` · `# Context` · `# Rules` · `# Output` · `# Examples`
 *
 * - Anthropic: separate `system` param, XML sections, `cache_control: ephemeral` on
 *   the stable Context block.
 * - OpenAI: first `system` message, Markdown headings (`# Role` then `## Section`).
 *   o-series models take no system message — the runtime adapter folds it into the
 *   first user turn (out of scope for the prompt renderer).
 */

const SECTION_RE = /^#\s+(\w[\w-]*)\s*$/;

/**
 * Split canonical Markdown into a `{ role, context, rules, output, examples }` map.
 * Comment blocks at the very top (HTML comments before the first `# Section`) are
 * dropped — they're authoring notes, not part of the prompt.
 */
export function extractSections(canonical) {
  const lines = String(canonical).split('\n');
  const sections = {};
  let current = null;
  let buf = [];
  const flush = () => {
    if (current) sections[current] = (sections[current] ? sections[current] + '\n' : '') + buf.join('\n').trim();
    buf = [];
  };
  for (const line of lines) {
    const match = SECTION_RE.exec(line);
    if (match) {
      flush();
      current = match[1].toLowerCase();
    } else if (current) {
      buf.push(line);
    }
  }
  flush();
  return sections;
}

/** Anthropic system-prompt form: XML sections, ephemeral cache on Context. */
export function renderAnthropic(sections) {
  const lines = ['<!-- Generated by agent-forge prompt-engineer (Fase 1) from system.canonical.md. Do not hand-edit. -->'];
  if (sections.role) lines.push(`<role>${sections.role}</role>`);
  if (sections.context) lines.push('', '<context cache="ephemeral">', sections.context, '</context>');
  if (sections.rules) lines.push('', '<rules>', sections.rules, '</rules>');
  if (sections.output) lines.push('', '<output>', sections.output, '</output>');
  if (sections.examples) lines.push('', '<examples>', sections.examples, '</examples>');
  return lines.join('\n') + '\n';
}

/** OpenAI system-message form: Markdown with `# Role` then `## Sections`. */
export function renderOpenAI(sections) {
  const lines = ['<!-- Generated by agent-forge prompt-engineer (Fase 1) from system.canonical.md. Do not hand-edit. -->'];
  if (sections.role) lines.push('# Role', sections.role);
  if (sections.context) lines.push('', '## Context', sections.context);
  if (sections.rules) lines.push('', '## Rules', sections.rules);
  if (sections.output) lines.push('', '## Output', sections.output);
  if (sections.examples) lines.push('', '## Examples', sections.examples);
  return lines.join('\n') + '\n';
}

/** One-stop renderer; returns `{ sections, anthropic, openai }`. */
export function generatePrompts(canonical) {
  const sections = extractSections(canonical);
  return {
    sections,
    anthropic: renderAnthropic(sections),
    openai: renderOpenAI(sections),
  };
}
