/**
 * render.mjs — shared body renderer for the F8 context bridges (ADR-0068).
 *
 * Every bridge file (Cursor, Copilot, Gemini, Windsurf, Aider, Continue) carries
 * the SAME context payload — a pointer to the real project constitution plus an
 * EXPLICIT "context-only, no enforcement" notice (ADR-0068 §3). Per-tool installers
 * wrap this body in whatever envelope the tool expects (frontmatter, file name)
 * and write it through `marker-inject.mjs` so re-installs never clobber user prose.
 *
 * Zero third-party deps — pure string assembly.
 */

/**
 * Renders the kit-owned context body for a bridge file.
 * @param {object} opts
 * @param {string} [opts.name]  project name (for the heading)
 * @param {string} [opts.label] tool label (e.g. "Cursor")
 * @returns {string} markdown body to place between the marker comments
 */
export function renderBridgeBody({ name, label } = {}) {
  const project = name || 'This project';
  const tool = label || 'this tool';
  return [
    `# ${project} — ContextDevKit context bridge`,
    '',
    `Generated by ContextDevKit for **${tool}** so it shares the same project context`,
    'as the native hosts. Keep edits surgical and match the surrounding style.',
    '',
    `> ⚠️ **Context only — no enforcement.** ContextDevKit governance (hooks, L5 gates,`,
    `> the session ledger, the pre-push quality gate) runs on the native hosts`,
    `> (Claude Code / Antigravity / Codex), **not** on ${tool}. The rules below are`,
    '> guidance for this tool; the enforced source of truth stays with the kit.',
    '',
    '## Where the real context lives',
    '',
    '- `CLAUDE.md` — the project constitution (rules, language policy, structure). Read it first.',
    '- `contextkit/best-practices.md` — code-quality rubric (file-size budget, SRP, naming).',
    '- `contextkit/behaviors.md` — how to work (think first, simplicity, surgical changes).',
    '- `contextkit/memory/decisions/` — ADRs: the *why* behind architectural choices.',
    '- `contextkit/memory/sessions/` — what changed, one entry per session.',
    '',
    '## Working agreement',
    '',
    '1. Read `CLAUDE.md` before non-trivial changes; respect its immutable rules.',
    '2. Keep changes surgical — no drive-by refactors; match the existing style.',
    '3. Prefer the smallest change that solves the problem.',
  ].join('\n');
}
