/**
 * Codex host installation - ContextDevKit's OpenAI Codex surface.
 *
 * Installs AGENTS.md, `.codex/` hooks/subagents, `source-command-*` Codex
 * skills under the project skill directory, and the `cdx.mjs` runner alias.
 * Claude remains the authored source; Codex assets are generated by build:codex.
 */
import { existsSync } from 'node:fs';
import { rm, rmdir } from 'node:fs/promises';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { CODEX_DIR, CODEX_SKILLS_DIR } from '../../templates/contextkit/runtime/config/paths.mjs';
import { composeCodexHooks } from '../../templates/contextkit/runtime/config/codex-hooks-compose.mjs';
import { detectStack } from './project.mjs';
import { read, overwrite, copyTree, render } from './fs.mjs';
import { stripMarkedBlockFile } from './lib/marker-inject.mjs';

const LEGACY_GLOBAL_ROUTING_START = '<!-- contextdevkit:codex-global-routing:start -->';
const LEGACY_GLOBAL_ROUTING_END = '<!-- contextdevkit:codex-global-routing:end -->';
const LEGACY_ROUTING_HARNESS_FILES = Object.freeze([
  'resolve-subagent-route.mjs',
  'resolve-subagent-route.selftest.mjs',
  'subagent-routing-policy.json',
]);

/**
 * Removes the known v3 project-level routing section without touching any
 * surrounding project instructions. ContextDevKit v4 routing is advisory.
 *
 * @param {string} contents current AGENTS.md contents
 * @returns {{changed:boolean,text:string}}
 */
export function removeLegacyProjectRoutingSection(contents) {
  const source = String(contents ?? '');
  const legacySection = /^### Codex-only mandatory subagent routing\s*$[\s\S]*?(?=^##\s|(?![\s\S]))/m;
  const text = source.replace(legacySection, '').replace(/\n{3,}/g, '\n\n');
  return { changed: text !== source, text };
}

/**
 * Removes only the globally installed v3 ContextDevKit routing block and the
 * three harness files that exclusively served it. User-authored global Codex
 * instructions outside the managed markers remain byte-preserved.
 *
 * @param {string} codexHome absolute Codex home directory
 * @param {string[]} report installer report sink
 * @returns {Promise<{removedBlock:boolean,removedHarnessFiles:number}>}
 */
export async function cleanupLegacyGlobalCodexRouting(codexHome, report = []) {
  const agentsPath = join(codexHome, 'AGENTS.md');
  const stripped = await stripMarkedBlockFile(agentsPath, {
    startMarker: LEGACY_GLOBAL_ROUTING_START,
    endMarker: LEGACY_GLOBAL_ROUTING_END,
  });
  if (!stripped.removed) return { removedBlock: false, removedHarnessFiles: 0 };

  if (stripped.empty) await rm(agentsPath, { force: true });
  let removedHarnessFiles = 0;
  const harnessDir = join(codexHome, 'harness');
  for (const filename of LEGACY_ROUTING_HARNESS_FILES) {
    const filePath = join(harnessDir, filename);
    if (!existsSync(filePath)) continue;
    await rm(filePath, { force: true });
    removedHarnessFiles += 1;
  }
  try { await rmdir(harnessDir); } catch { /* Preserve a non-empty user-owned harness directory. */ }
  report.push(`✓ removed legacy mandatory Codex routing block${removedHarnessFiles ? ` and ${removedHarnessFiles} obsolete harness file(s)` : ''}`);
  return { removedBlock: true, removedHarnessFiles };
}

async function patchPackageScripts(target, report) {
  const pkgPath = join(target, 'package.json');
  if (!existsSync(pkgPath)) return;
  try {
    const pkg = JSON.parse(await read(pkgPath));
    if (!pkg.scripts) pkg.scripts = {};
    if (pkg.scripts.cdx === 'node cdx.mjs') return;
    pkg.scripts.cdx = 'node cdx.mjs';
    await overwrite(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
    report.push('✓ package.json patched with "cdx" script shortcut');
  } catch (err) {
    report.push(`WARN failed to patch package.json for Codex: ${err.message}`);
  }
}

async function renderAgentsMd(target, tplDir, ctx) {
  const tpl = await read(join(tplDir, 'AGENTS.md.tpl'));
  return render(tpl, {
    PROJECT_NAME: ctx.name,
    DATE: new Date().toISOString().slice(0, 10),
    LEVEL: String(ctx.level),
    MODE: ctx.mode,
    STACK_NOTES: ctx.mode === 'existing' ? await detectStack(target) : 'Greenfield - define the stack as the first architectural decision.',
  });
}

async function installAgentsMd(target, tplDir, ctx, report) {
  const agentsPath = join(target, 'AGENTS.md');
  const out = await renderAgentsMd(target, tplDir, ctx);
  if (ctx.args.update && existsSync(agentsPath) && !ctx.args.force) {
    const existing = await read(agentsPath);
    const cleaned = removeLegacyProjectRoutingSection(existing);
    const current = cleaned.text;
    if (cleaned.changed) {
      await overwrite(agentsPath, current);
      report.push('✓ removed legacy mandatory routing section from AGENTS.md');
    }
    if (current === out) return;
    await overwrite(join(target, 'AGENTS.contextdevkit.md'), out);
    report.push('WARN AGENTS.md exists - wrote refreshed AGENTS.contextdevkit.md to merge by hand');
    return;
  }
  if (!existsSync(agentsPath) || ctx.args.force) {
    await overwrite(agentsPath, out);
    report.push('✓ AGENTS.md created');
  } else {
    await overwrite(join(target, 'AGENTS.contextdevkit.md'), out);
    report.push('WARN AGENTS.md exists - wrote AGENTS.contextdevkit.md to merge by hand');
  }
}

async function wireCodexHooks(target, level, report) {
  const hooksPath = join(target, CODEX_DIR, 'hooks.json');
  let existing = null;
  if (existsSync(hooksPath)) {
    try {
      existing = JSON.parse((await read(hooksPath)).replace(/^\uFEFF/, ''));
    } catch {
      report.push(`WARN ${CODEX_DIR}/hooks.json is not valid JSON - left untouched, fix or delete it and re-run`);
      return;
    }
  }
  await overwrite(hooksPath, JSON.stringify(composeCodexHooks(existing, level), null, 2) + '\n');
  report.push(`✓ Codex hooks wired (${CODEX_DIR}/hooks.json, level ${level})`);
}

export async function installCodexHost(target, tplDir, ctx, report) {
  const codexHome = process.env.CODEX_HOME || join(homedir(), '.codex');
  try {
    await cleanupLegacyGlobalCodexRouting(codexHome, report);
  } catch (error) {
    report.push(`WARN could not remove legacy mandatory Codex routing: ${error?.message ?? error}`);
  }
  await overwrite(join(target, 'cdx.mjs'), await read(join(tplDir, 'cdx.mjs')));
  report.push('✓ Codex CLI runner installed (cdx.mjs)');
  await patchPackageScripts(target, report);

  await copyTree(join(tplDir, 'codex', 'skills'), join(target, CODEX_SKILLS_DIR));
  report.push(`✓ Codex source-command skills installed (${CODEX_SKILLS_DIR}/source-command-*)`);

  await overwrite(join(target, CODEX_DIR, 'README.md'), await read(join(tplDir, 'codex', 'README.md')));
  if (ctx.level >= 4) {
    await copyTree(join(tplDir, 'codex', 'agents'), join(target, CODEX_DIR, 'agents'));
    report.push(`✓ Codex subagents installed (${CODEX_DIR}/agents)`);
  }

  await wireCodexHooks(target, ctx.level, report);
  await installAgentsMd(target, tplDir, ctx, report);
}
