/**
 * Model router for agent-forge (ADR-0012). Reads `decision-rules.json` + the
 * `capability-matrix.json`, applies deterministic SHORTLIST rules to a parsed
 * Agent Blueprint, filters candidates by capability + residency, and emits a
 * { primary, fallback, cheap_path, premium_path, applied_rules, rationale }
 * decision. Quality opinions live in the eval harness, NOT here (ADR-0012 §5).
 *
 * Pure zero-dep (rule 1) — no provider SDKs, no YAML, just `node:` + JSON.parse.
 * The architect/orchestrator parses YAML upstream via `lib/yaml.mjs` and hands
 * `routeAgent` a plain JS object.
 */
import { readFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const DEFAULT_MATRIX = resolve(HERE, '..', 'router', 'capability-matrix.json');
const DEFAULT_RULES = resolve(HERE, '..', 'router', 'decision-rules.json');

async function loadJson(path) {
  const raw = await readFile(path, 'utf-8');
  return JSON.parse(raw.replace(/^﻿/, ''));
}

export async function loadMatrix(path = DEFAULT_MATRIX) {
  return loadJson(path);
}

export async function loadRules(path = DEFAULT_RULES) {
  return loadJson(path);
}

function getPath(source, dotPath) {
  return dotPath.split('.').reduce((node, key) => node?.[key], source);
}

function matchOne(actual, expected) {
  if (expected && typeof expected === 'object' && !Array.isArray(expected)) {
    for (const [op, ref] of Object.entries(expected)) {
      if (op === '$eq' && actual !== ref) return false;
      if (op === '$gt' && !(actual > ref)) return false;
      if (op === '$gte' && !(actual >= ref)) return false;
      if (op === '$lt' && !(actual < ref)) return false;
      if (op === '$lte' && !(actual <= ref)) return false;
    }
    return true;
  }
  if (Array.isArray(expected)) return expected.includes(actual);
  return actual === expected;
}

function matchesWhen(when, blueprint) {
  if (!when || !Object.keys(when).length) return true;
  return Object.entries(when).every(([dotPath, expected]) => matchOne(getPath(blueprint, dotPath), expected));
}

function isAvailable(model, blueprint) {
  if (!model) return false;
  const caps = blueprint.capabilities || {};
  const priv = blueprint.privacy || {};
  if (caps.tools && model.capabilities?.tools === false) return false;
  if ((caps.multimodal || blueprint.intent?.multimodal) && model.capabilities?.vision === false) return false;
  if (caps.structured_output && model.capabilities?.structured_output === false) return false;
  if (priv.allow_cloud_providers === false && !model.id.startsWith('self-hosted/')) return false;
  if (priv.data_residency === 'on-prem' && !model.id.startsWith('self-hosted/')) return false;
  return true;
}

function firstAvailable(ids, modelById, blueprint) {
  for (const id of ids) {
    if (isAvailable(modelById[id], blueprint)) return id;
  }
  return undefined;
}

function buildRationale(ctx) {
  const { primary, fallback, cheap_path, premium_path, applied_rules, blueprint } = ctx;
  const intent = blueprint.intent || {};
  const facts = [`intent: ${intent.category || '?'}${intent.complexity ? ' (' + intent.complexity + ')' : ''}`];
  if (intent.multimodal || blueprint.capabilities?.multimodal) facts.push('multimodal required');
  if (blueprint.capabilities?.tools) facts.push('tool use required');
  if (blueprint.privacy?.data_residency) facts.push(`residency: ${blueprint.privacy.data_residency}`);
  if (blueprint.privacy?.allow_cloud_providers === false) facts.push('no-cloud (self-hosted only)');

  const sameProvider = fallback && primary.split('/')[0] === fallback.split('/')[0];
  const ruleTrace = applied_rules.length ? applied_rules.map((rule) => '`' + rule + '`').join(', ') : '`default-balanced`';
  const lines = [
    '## Model Selection Rationale',
    '',
    `<!-- Generated by agent-forge model-router. Applied rules: ${applied_rules.join(' → ') || '(default)'}. -->`,
    `> **Authority:** the eval harness (golden + red-team) measured on your dataset, not these rules ([ADR-0012](../../memory/decisions/0012-agent-forge-squad-for-portable-agent-packages.md) §5).`,
    '',
    `**Primary:** \`${primary}\``,
    `- Constraints applied: ${facts.join('; ')}.`,
    `- Selected from the shortlist of rule(s): ${ruleTrace}.`,
  ];
  if (fallback) {
    lines.push('');
    lines.push(`**Fallback:** \`${fallback}\``);
    lines.push(`- ${sameProvider ? 'WARN: same provider as primary — outage defense weakened. Review.' : 'Different provider from primary — outage defense.'}`);
  } else {
    lines.push('');
    lines.push('**Fallback:** _no cross-provider candidate was available_. The eval gate may flag this — extend `decision-rules.json` or relax residency.');
  }
  if (cheap_path) {
    lines.push('');
    lines.push(`**Cheap path:** \`${cheap_path}\` — for cheap sub-tasks.`);
  }
  if (premium_path) {
    lines.push('');
    lines.push(`**Premium path:** \`${premium_path}\` — for calls flagged critical.`);
  }
  return lines.join('\n');
}

export async function routeAgent(blueprint, opts = {}) {
  const matrix = opts.matrix ?? (await loadMatrix(opts.matrixPath));
  const rules = opts.rules ?? (await loadRules(opts.rulesPath));
  const cap = rules.max_rules ?? 15;
  if (rules.rules.length > cap) {
    throw new Error(`agent-forge router: decision-rules has ${rules.rules.length} rules (cap ${cap}). Split by intent category — blueprint §12.`);
  }
  const modelById = Object.fromEntries(matrix.models.map((model) => [model.id, model]));

  const matched = [];
  const primaryCandidates = [];
  const fallbackCandidates = [];
  let cheapPath;
  let premiumPath;
  let abortIfEmpty = false;

  for (const rule of rules.rules) {
    if (!matchesWhen(rule.when, blueprint)) continue;
    matched.push(rule.id);
    if (rule.then?.primary_candidates) primaryCandidates.push(...rule.then.primary_candidates);
    if (rule.then?.fallback_candidates) fallbackCandidates.push(...rule.then.fallback_candidates);
    if (rule.then?.cheap_path && !cheapPath) cheapPath = rule.then.cheap_path;
    if (rule.then?.premium_path && !premiumPath) premiumPath = rule.then.premium_path;
    if (rule.abort_if_no_candidate) abortIfEmpty = true;
  }

  const primary = firstAvailable(primaryCandidates, modelById, blueprint);
  if (!primary) {
    if (abortIfEmpty) {
      throw new Error('agent-forge router: no candidate satisfies the blueprint constraints (residency/capabilities). Review the blueprint or extend decision-rules.');
    }
    throw new Error('agent-forge router: no matching rule produced an available primary candidate — add a default-balanced rule or specify capabilities precisely.');
  }

  const primaryProvider = primary.split('/')[0];
  const allFallbacks = [...fallbackCandidates, ...primaryCandidates.filter((id) => id !== primary)];
  const fallback = allFallbacks.find((id) => id.split('/')[0] !== primaryProvider && isAvailable(modelById[id], blueprint));

  const cheapAvail = cheapPath && isAvailable(modelById[cheapPath], blueprint) ? cheapPath : undefined;
  const premiumAvail = premiumPath && isAvailable(modelById[premiumPath], blueprint) ? premiumPath : undefined;

  return {
    primary,
    fallback,
    cheap_path: cheapAvail,
    premium_path: premiumAvail,
    applied_rules: matched,
    rationale: buildRationale({ primary, fallback, cheap_path: cheapAvail, premium_path: premiumAvail, applied_rules: matched, blueprint }),
  };
}
