#!/usr/bin/env node
/**
 * `changelog-rotate.mjs` — rotate closed majors out of the head changelog.
 *
 * ONE responsibility: keep `CHANGELOG.md` at `[Unreleased]` + the current major
 * and move every closed major into `docs/changelog/vN.md` behind a generated
 * index. It does NOT parse commits (that is `draft-changelog.mjs`) and it does
 * NOT deduplicate — when it finds a structural anomaly it REFUSES, because
 * silently rewriting release history is worse than stopping.
 *
 * Posture (constitution §8): DRY-RUN BY DEFAULT. `--write` applies atomically
 * (tmp + rename via `safe-io`). `--check` is the CI gate. A detectable anomaly
 * is never reported as "skipped" and never as a pass.
 *
 * The head file is the SOURCE for the preamble; sections are gathered from the
 * head AND the existing archive, so a second run sees the same corpus and is
 * byte-identical (idempotence) instead of "forgetting" already-archived majors.
 *
 * Exit codes: 0 clean/in-sync · 1 anomaly or drift (the blocking signal) ·
 * 2 unusable input (missing/unparseable head file).
 *
 * Zero runtime dependencies — `node:*` + `safe-io` only (immutable rule 1).
 *
 * Usage:
 *   node contextkit/tools/scripts/changelog-rotate.mjs [root]           # plan
 *   node contextkit/tools/scripts/changelog-rotate.mjs [root] --write   # apply
 *   node contextkit/tools/scripts/changelog-rotate.mjs [root] --check   # CI gate
 *   node contextkit/tools/scripts/changelog-rotate.mjs [root] --json
 */
import { existsSync, mkdirSync, readFileSync, readdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { writeFileAtomicSync } from '../../runtime/hooks/safe-io.mjs';

/** Head changelog, relative to the project root. */
const HEAD_FILE = 'CHANGELOG.md';
/** Archive directory holding one file per closed major, plus the index. */
const ARCHIVE_DIR = join('docs', 'changelog');
/** Marker pair fencing the generated navigation note in the head preamble. */
const NAV_START = '<!-- contextdevkit:changelog-archive:start -->';
const NAV_END = '<!-- contextdevkit:changelog-archive:end -->';
/** Provenance line stamped into every fully generated archive artifact. */
const PROVENANCE = '> Generated by `changelog-rotate.mjs` — do not edit by hand.';

/** Strips a UTF-8 BOM so downstream parsing never trips on it (rule 4). */
function deBom(text) {
  return text.charCodeAt(0) === 0xfeff ? text.slice(1) : text;
}

/** True when the line opens or closes a fenced code block. */
function isFence(line) {
  return /^\s{0,3}(```|~~~)/.test(line);
}

/** The `[version]` of a release heading, or null when the line is not one. */
function headingVersion(line) {
  const match = /^##\s+\[([^\]]+)\]/.exec(line);
  return match ? match[1].trim() : null;
}

/** The numeric major of a version string, or null when unparseable. */
function majorOf(version) {
  const match = /^v?(\d+)\./.exec(String(version ?? ''));
  return match ? Number(match[1]) : null;
}

/** Numeric identifiers of a version, ignoring any pre-release suffix. */
function releaseParts(version) {
  const core = String(version ?? '').replace(/^v/, '').split(/[-+]/)[0];
  return core.split('.').map((part) => Number.parseInt(part, 10) || 0);
}

/**
 * Parses a changelog into its preamble and ordered sections.
 *
 * Fence-aware: a `## [x.y.z]` line inside a code block is prose, never a
 * version. Tolerates a BOM and CRLF. Pure — no I/O.
 *
 * @param {string} text - raw changelog contents.
 * @returns {{preamble: string[], sections: Array<{kind: 'unreleased'|'release', version: string|null, lines: string[]}>}}
 */
export function parseChangelogSections(text) {
  const lines = deBom(String(text ?? '')).split(/\r?\n/);
  const preamble = [];
  const sections = [];
  let current = null;
  let inFence = false;

  for (const line of lines) {
    const fence = isFence(line);
    const version = fence || inFence ? null : headingVersion(line);
    if (version !== null) {
      current = {
        kind: /^unreleased$/i.test(version) ? 'unreleased' : 'release',
        version: /^unreleased$/i.test(version) ? null : version,
        lines: [line],
      };
      sections.push(current);
      continue;
    }
    if (fence) inFence = !inFence;
    if (current) current.lines.push(line);
    else preamble.push(line);
  }

  return { preamble, sections };
}

/** Bullet lines of a section, grouped by their `###` subsection heading. */
function bulletsBySubsection(sectionLines) {
  const groups = new Map();
  let subsection = '(root)';
  let inFence = false;
  for (const line of sectionLines) {
    if (isFence(line)) { inFence = !inFence; continue; }
    if (inFence) continue;
    if (/^###\s+/.test(line)) { subsection = line.trim(); continue; }
    if (/^\s*[-*]\s+\S/.test(line)) {
      if (!groups.has(subsection)) groups.set(subsection, []);
      groups.get(subsection).push(line.trim());
    }
  }
  return groups;
}

/**
 * Finds structural anomalies that must block a write.
 *
 * Three classes: a version heading that appears twice, an identical bullet
 * repeated inside one subsection, and a version whose major cannot be parsed.
 * Returns `[]` when clean; NEVER mutates or normalizes the input — a duplicate
 * is a human correction, not an automatic rewrite.
 *
 * @param {ReturnType<typeof parseChangelogSections>} parsed
 * @returns {Array<{kind: string, version: string|null, detail: string}>}
 */
export function detectDuplicateEntries(parsed) {
  const sections = parsed?.sections ?? [];
  const findings = [];
  const seenVersions = new Set();

  for (const section of sections) {
    if (section.kind === 'release') {
      if (seenVersions.has(section.version)) {
        findings.push({ kind: 'duplicate-version', version: section.version, detail: `version [${section.version}] appears more than once` });
      }
      seenVersions.add(section.version);
      if (majorOf(section.version) === null) {
        findings.push({ kind: 'unparseable-version', version: section.version, detail: `version [${section.version}] has no parseable major` });
      }
    }
    for (const [subsection, bullets] of bulletsBySubsection(section.lines)) {
      const seen = new Set();
      for (const bullet of bullets) {
        if (seen.has(bullet)) {
          const label = section.version ? `[${section.version}]` : '[Unreleased]';
          findings.push({
            kind: 'duplicate-entry',
            version: section.version,
            detail: `duplicated entry in ${label} ${subsection}: ${bullet.slice(0, 80)}`,
          });
        }
        seen.add(bullet);
      }
    }
  }
  return findings;
}

/**
 * Compares two semantic versions numerically.
 *
 * Component-wise on the release identifiers, then a release sorts ABOVE its own
 * pre-release (`3.7.0` > `3.7.0-rc.1`). Pure.
 *
 * @param {string} left
 * @param {string} right
 * @returns {number} negative, zero or positive, for use as a sort comparator.
 */
export function compareSemVer(left, right) {
  const leftParts = releaseParts(left);
  const rightParts = releaseParts(right);
  for (let index = 0; index < Math.max(leftParts.length, rightParts.length); index += 1) {
    const delta = (leftParts[index] ?? 0) - (rightParts[index] ?? 0);
    if (delta !== 0) return delta;
  }
  const leftPre = /-/.test(String(left));
  const rightPre = /-/.test(String(right));
  if (leftPre === rightPre) return String(right).localeCompare(String(left));
  return leftPre ? -1 : 1;
}

/**
 * Buckets release sections by major version, newest version first inside each.
 *
 * A pre-release buckets with its OWN major (`2.0.0-rc.1` → 2). A version with no
 * parseable major is skipped here and reported by `detectDuplicateEntries`, so it
 * is never silently dropped. Pure.
 *
 * @param {ReturnType<typeof parseChangelogSections>} parsed
 * @returns {Map<number, Array<{kind: string, version: string|null, lines: string[]}>>}
 */
export function splitByMajor(parsed) {
  const buckets = new Map();
  for (const section of parsed?.sections ?? []) {
    if (section.kind !== 'release') continue;
    const major = majorOf(section.version);
    if (major === null) continue;
    if (!buckets.has(major)) buckets.set(major, []);
    buckets.get(major).push(section);
  }
  for (const sections of buckets.values()) {
    sections.sort((left, right) => compareSemVer(right.version, left.version));
  }
  return buckets;
}

// ---------------------------------------------------------------------------
// Rendering — pure text assembly from the parsed corpus
// ---------------------------------------------------------------------------

/** Section text with trailing blank lines trimmed. */
function sectionText(section) {
  const lines = [...section.lines];
  while (lines.length && lines[lines.length - 1].trim() === '') lines.pop();
  return lines.join('\n');
}

/** Preamble with any previously generated navigation block removed. */
function preambleWithoutNav(preamble) {
  const kept = [];
  let skipping = false;
  for (const line of preamble) {
    if (line.includes(NAV_START)) { skipping = true; continue; }
    if (line.includes(NAV_END)) { skipping = false; continue; }
    if (!skipping) kept.push(line);
  }
  while (kept.length && kept[kept.length - 1].trim() === '') kept.pop();
  return kept;
}

/** The head file: preamble + navigation note + unreleased + current major. */
function renderHead(parsed, currentMajor, archivedMajors) {
  const blocks = [preambleWithoutNav(parsed.preamble).join('\n')];
  if (archivedMajors.length) {
    blocks.push([
      NAV_START,
      `> **Older history is archived.** This file keeps \`[Unreleased]\` and the ${currentMajor}.x`,
      '> series; earlier majors live in [`docs/changelog/`](docs/changelog/README.md)',
      `> (${archivedMajors.map((major) => `\`v${major}.md\``).join(', ')}).`,
      NAV_END,
    ].join('\n'));
  }
  for (const section of parsed.sections) {
    if (section.kind === 'unreleased') blocks.push(sectionText(section));
  }
  const buckets = splitByMajor(parsed);
  for (const section of buckets.get(currentMajor) ?? []) blocks.push(sectionText(section));
  return `${blocks.filter(Boolean).join('\n\n')}\n`;
}

/** One archive file per closed major. */
function renderArchive(major, sections) {
  const header = [
    `# Changelog — ${major}.x`,
    PROVENANCE,
    '> Closed major series. See [the index](README.md) for every released version,',
    '> and [`CHANGELOG.md`](../../CHANGELOG.md) for the current series.',
  ].join('\n');
  return `${[header, ...sections.map(sectionText)].join('\n\n')}\n`;
}

/** The archive index: every released version and where it lives. */
function renderIndex(buckets, currentMajor) {
  const majors = [...buckets.keys()].sort((left, right) => right - left);
  const rows = [];
  for (const major of majors) {
    const location = major === currentMajor ? '[`CHANGELOG.md`](../../CHANGELOG.md)' : `[\`v${major}.md\`](v${major}.md)`;
    for (const section of buckets.get(major)) {
      const heading = section.lines[0] ?? '';
      const date = /\]\s*-\s*(\S+)/.exec(heading);
      rows.push(`| \`${section.version}\` | ${date ? date[1] : '—'} | ${location} |`);
    }
  }
  return [
    '# Changelog index',
    '',
    PROVENANCE,
    '',
    'Every released version of this project, newest first. The current series stays',
    'in the repository-root changelog; closed majors are archived beside this index.',
    '',
    '| Version | Date | Where |',
    '| --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Corpus gathering — head + existing archive, so a re-run sees the same input
// ---------------------------------------------------------------------------

/** Defensive UTF-8 read; '' when missing or unreadable (rule 2). */
function readText(path) {
  if (!existsSync(path)) return '';
  try { return readFileSync(path, 'utf-8'); } catch { return ''; }
}

/** Existing `vN.md` archive files, ascending by major. */
function archiveFiles(archiveDir) {
  if (!existsSync(archiveDir)) return [];
  try {
    return readdirSync(archiveDir)
      .filter((name) => /^v\d+\.md$/.test(name))
      .sort((left, right) => Number(left.slice(1)) - Number(right.slice(1)));
  } catch { return []; }
}

/**
 * Builds the full corpus: the head preamble plus every section found in the head
 * AND the archive, so an already-rotated tree re-renders identically.
 *
 * @param {string} root - project root.
 * @returns {{ok: boolean, reason?: string, parsed?: object}}
 */
function gatherCorpus(root) {
  const headText = readText(resolve(root, HEAD_FILE));
  if (!headText.trim()) return { ok: false, reason: `${HEAD_FILE} is missing or empty` };

  const head = parseChangelogSections(headText);
  const sections = [...head.sections];
  const archiveDir = resolve(root, ARCHIVE_DIR);
  for (const name of archiveFiles(archiveDir)) {
    for (const section of parseChangelogSections(readText(join(archiveDir, name))).sections) {
      if (section.kind === 'release') sections.push(section);
    }
  }
  if (!sections.some((section) => section.kind === 'release')) {
    return { ok: false, reason: `${HEAD_FILE} contains no release heading (## [x.y.z])` };
  }
  return { ok: true, parsed: { preamble: head.preamble, sections } };
}

/**
 * Computes the target state of every file the rotation owns.
 *
 * @param {string} root - project root.
 * @returns {{ok: boolean, reason?: string, findings?: object[], currentMajor?: number, archivedMajors?: number[], targets?: Array<{path: string, relPath: string, text: string, changed: boolean}>}}
 */
function planRotation(root) {
  const corpus = gatherCorpus(root);
  if (!corpus.ok) return { ok: false, reason: corpus.reason };

  const findings = detectDuplicateEntries(corpus.parsed);
  const buckets = splitByMajor(corpus.parsed);
  const majors = [...buckets.keys()].sort((left, right) => right - left);
  const currentMajor = majors[0];
  const archivedMajors = majors.filter((major) => major !== currentMajor);

  const targets = [{
    relPath: HEAD_FILE,
    path: resolve(root, HEAD_FILE),
    text: renderHead(corpus.parsed, currentMajor, archivedMajors),
  }];
  for (const major of archivedMajors) {
    targets.push({
      relPath: `${ARCHIVE_DIR}/v${major}.md`.replaceAll('\\', '/'),
      path: resolve(root, ARCHIVE_DIR, `v${major}.md`),
      text: renderArchive(major, buckets.get(major)),
    });
  }
  if (archivedMajors.length) {
    targets.push({
      relPath: `${ARCHIVE_DIR}/README.md`.replaceAll('\\', '/'),
      path: resolve(root, ARCHIVE_DIR, 'README.md'),
      text: renderIndex(buckets, currentMajor),
    });
  }
  for (const target of targets) target.changed = readText(target.path) !== target.text;

  return { ok: true, findings, currentMajor, archivedMajors, targets };
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

/** Prints findings; returns true when any exists. */
function reportFindings(findings) {
  if (!findings.length) return false;
  console.error(`changelog-rotate: REFUSED — ${findings.length} structural anomaly(ies) found:`);
  for (const finding of findings) console.error(`  ✗ ${finding.kind}: ${finding.detail}`);
  console.error('  Fix these by hand (a duplicate is a human correction, never an automatic rewrite), then re-run.');
  return true;
}

function main() {
  const argv = process.argv.slice(2);
  const flags = new Set(argv.filter((arg) => arg.startsWith('--')));
  const root = resolve(argv.find((arg) => !arg.startsWith('--')) ?? process.cwd());
  const asJson = flags.has('--json');
  const write = flags.has('--write');
  const check = flags.has('--check');

  const plan = planRotation(root);
  if (!plan.ok) {
    if (asJson) console.log(JSON.stringify({ ok: false, reason: plan.reason }, null, 2));
    else console.error(`changelog-rotate: unusable input — ${plan.reason}`);
    process.exit(2);
  }

  const changed = plan.targets.filter((target) => target.changed);
  const archived = plan.archivedMajors.map((major) => `${major}.x`).join(', ');

  if (asJson) {
    console.log(JSON.stringify({
      ok: plan.findings.length === 0 && (!check || changed.length === 0),
      mode: write ? 'write' : check ? 'check' : 'dry-run',
      currentMajor: plan.currentMajor,
      archivedMajors: plan.archivedMajors,
      findings: plan.findings,
      changed: changed.map((target) => target.relPath),
    }, null, 2));
    process.exit(plan.findings.length || (check && changed.length) ? 1 : 0);
  }

  if (reportFindings(plan.findings)) process.exit(1);

  if (check) {
    if (changed.length === 0) {
      console.log(`changelog-rotate: in sync — head keeps ${plan.currentMajor}.x${archived ? `, archived ${archived}` : ''}.`);
      process.exit(0);
    }
    console.error(`changelog-rotate: OUT OF SYNC — ${changed.length} file(s) would change:`);
    for (const target of changed) console.error(`  ✗ ${target.relPath}`);
    console.error('  Regenerate with: node contextkit/tools/scripts/changelog-rotate.mjs --write');
    process.exit(1);
  }

  if (!write) {
    console.log(`changelog-rotate: dry-run (pass --write to apply) — head keeps ${plan.currentMajor}.x`);
    if (plan.archivedMajors.length) console.log(`  archives: ${plan.archivedMajors.map((major) => `v${major}.md`).join(', ')}`);
    if (changed.length === 0) console.log('  already in sync — nothing would change.');
    for (const target of changed) console.log(`  would write ${target.relPath}`);
    process.exit(0);
  }

  if (plan.archivedMajors.length) mkdirSync(resolve(root, ARCHIVE_DIR), { recursive: true });
  for (const target of changed) writeFileAtomicSync(target.path, target.text);
  console.log(`changelog-rotate: wrote ${changed.length} file(s) — head keeps ${plan.currentMajor}.x${archived ? `, archived ${archived}` : ''}.`);
  process.exit(0);
}

const invokedDirectly = process.argv[1] && /changelog-rotate\.mjs$/.test(process.argv[1]);
if (invokedDirectly) main();
