#!/usr/bin/env node
/**
 * Regenerates `contextkit/memory/DELIBERATIONS.md` as an INDEX of the per-debate
 * markdown files under `contextkit/memory/deliberations/` (ADR-0035).
 *
 * A deliberation is pre-decision working material (independent voices debate a
 * hard question, a synthesizer converges). Like SESSIONS.md, the aggregate is
 * DERIVED from filesystem state so parallel sessions never fight over one file.
 *
 * Entry naming: `<YYYY-MM-DD>-<NN>-<slug>.md`
 *   - NN: zero-padded monotonic number.
 *   - slug: `[a-z0-9._-]` (kebab-case).
 *
 * Usage:  node contextkit/tools/scripts/deliberations-reindex.mjs
 *         (also wired into the pre-commit git hook)
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathsFor } from '../../runtime/config/paths.mjs';

const ROOT = process.cwd();
const P = pathsFor(ROOT);
const DELIBERATIONS_DIR = P.deliberations;
const INDEX_PATH = P.deliberationsIndex;
const ENTRY_PATTERN = /^(\d{4}-\d{2}-\d{2})-(\d{2,})-([a-z0-9._-]+)\.md$/;

/**
 * Pulls the `# ` heading (title) and `- **Status**:` value out of one file.
 * Defensive: a malformed file degrades to the slug + an `unknown` status rather
 * than aborting the whole index (rule 2 — never break real work).
 *
 * @param {string} filePath  absolute path to the deliberation file
 * @param {string} fallbackSlug  used as the title when no heading is present
 * @returns {Promise<{ title: string, status: string }>}
 */
async function extractMeta(filePath, fallbackSlug) {
  try {
    const content = await readFile(filePath, 'utf-8');
    const lines = content.split('\n');
    const heading = lines.find((l) => l.startsWith('# '));
    const statusLine = lines.find((l) => /^\s*-\s*\*\*Status\*\*:/i.test(l));
    const status = statusLine ? (statusLine.match(/:\s*([a-z]+)/i)?.[1]?.toLowerCase() ?? 'unknown') : 'unknown';
    return { title: heading ? heading.slice(2).trim() : fallbackSlug, status };
  } catch {
    return { title: fallbackSlug, status: 'unknown' };
  }
}

async function listEntries() {
  let files = [];
  try {
    files = await readdir(DELIBERATIONS_DIR);
  } catch {
    return [];
  }
  const entries = [];
  for (const filename of files) {
    const match = ENTRY_PATTERN.exec(filename);
    if (!match) continue;
    const [, date, numberStr, slug] = match;
    const { title, status } = await extractMeta(resolve(DELIBERATIONS_DIR, filename), slug);
    entries.push({ filename, date, number: Number.parseInt(numberStr, 10), slug, title, status });
  }
  entries.sort((a, b) => (b.number !== a.number ? b.number - a.number : b.date.localeCompare(a.date)));
  return entries;
}

function statusBadge(status) {
  if (status === 'resolved') return '✅ resolved';
  if (status === 'unresolved') return '⚖️ unresolved';
  return '· —';
}

function buildIndex(entries) {
  const out = [];
  out.push('# Deliberation History');
  out.push('');
  out.push('> ⚠️  **AUTO-GENERATED FILE — DO NOT EDIT BY HAND**.');
  out.push('> Each debate lives in its own file under `contextkit/memory/deliberations/`.');
  out.push('> Regenerated by `deliberations-reindex` (also runs on pre-commit).');
  out.push('');
  out.push('Open a new deliberation with `/debate <question>`.');
  out.push('');
  if (entries.length === 0) {
    out.push('_(No deliberations recorded yet.)_');
    out.push('');
    return out.join('\n');
  }
  out.push(`Total recorded deliberations: **${entries.length}** (newest first).`);
  out.push('');
  out.push('| # | Date | Status | Question | File |');
  out.push('| --- | --- | --- | --- | --- |');
  for (const e of entries) {
    out.push(
      `| ${String(e.number).padStart(2, '0')} | ${e.date} | ${statusBadge(e.status)} | ${e.title} | [${e.filename}](deliberations/${e.filename}) |`,
    );
  }
  out.push('');
  return out.join('\n');
}

async function main() {
  const entries = await listEntries();
  await writeFile(INDEX_PATH, buildIndex(entries), 'utf-8');
  console.log(`✅ DELIBERATIONS.md regenerated — ${entries.length} entries indexed.`);
}

main().catch((err) => {
  console.error('❌ Failed to reindex deliberations:', err);
  process.exit(1);
});
