#!/usr/bin/env node
/**
 * `/docs-reindex` — apply/maintain the Diátaxis documentation spine (ADR-0030).
 *
 * Diátaxis (https://diataxis.fr/) sorts docs by READER INTENT into four modes:
 * tutorials (learning) · how-to (task) · reference (information) · explanation
 * (understanding). This script ENSURES that structure exists and REGENERATES the
 * canonical English `docs/README.md` navigation index.
 *
 * Localized documentation roots are declared in `docs/locales.json`. Non-canonical
 * locale trees are intentionally excluded from the English Diátaxis index so
 * translated pages never appear as duplicate/unclassified English documents.
 * Each locale owns its own README/navigation surface.
 *
 * Reorganize-without-losing (the installer runs it on `--update`): it NEVER moves,
 * renames, or deletes a content file. It only (a) creates the four bucket dirs +
 * their README stub write-if-missing, and (b) rewrites the auto-owned index. A doc
 * is classified by `docs/.diataxis.json` (explicit `{ "<relpath>": "<bucket>" }`),
 * then by the bucket folder it already lives in, then by a filename heuristic;
 * unmatched canonical docs are listed under "Unclassified" so nothing is silently
 * dropped (constitution §8). Zero runtime deps (rule 1); idempotent.
 *
 * Usage:
 *   node contextkit/tools/scripts/docs-reindex.mjs           # reindex ./docs
 *   node contextkit/tools/scripts/docs-reindex.mjs --json
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { resolve, join, relative } from 'node:path';

const INDEX_MARKER = 'AUTO-GENERATED by docs-reindex.mjs';
const BUCKETS = ['tutorials', 'how-to', 'reference', 'explanation'];
const BUCKET_META = {
  tutorials: { icon: '🎓', tag: 'learning-oriented', blurb: 'Lessons that take a newcomer by the hand through a first success.' },
  'how-to': { icon: '🔧', tag: 'task-oriented', blurb: 'Recipes that solve a specific real-world problem for someone who already knows the basics.' },
  reference: { icon: '📚', tag: 'information-oriented', blurb: 'Dry, accurate technical descriptions — formats, options, APIs. Consulted, not read.' },
  explanation: { icon: '💡', tag: 'understanding-oriented', blurb: 'Background and rationale — the why behind the decisions.' },
};
const META_FILES = new Set(['roadmap.md', 'changelog.md']);

/**
 * Resolve deterministic planning/meta inclusion rules from `.diataxis.json`.
 * Git metadata is intentionally irrelevant so ZIP, tarball, and plain-directory
 * installs render the same tree. An explicit include wins over an exclude.
 * @param {Record<string, unknown>} map parsed Diataxis map
 * @returns {{include:Set<string>,exclude:Set<string>}}
 */
function metaFileRules(map) {
  const policy = map?._metaFiles;
  const normalize = (entries) => new Set(
    (Array.isArray(entries) ? entries : [])
      .filter((entry) => typeof entry === 'string')
      .map((entry) => entry.replace(/\\/g, '/').toLowerCase()),
  );
  return { include: normalize(policy?.include), exclude: normalize(policy?.exclude) };
}

/**
 * Resolve locale roots that must not be folded into the canonical English index.
 * `docs/locales.json` is advisory metadata for documentation tooling only; malformed
 * or absent data degrades to no excluded roots rather than breaking reindex.
 *
 * @param {string} docsDir absolute docs root
 * @returns {Set<string>} first path segments for non-canonical locale roots
 */
function localizedRoots(docsDir) {
  const manifestPath = join(docsDir, 'locales.json');
  if (!existsSync(manifestPath)) return new Set();
  try {
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8').replace(/^﻿/, ''));
    const canonical = String(manifest?.canonicalLocale ?? 'en');
    const roots = new Set();
    for (const locale of Array.isArray(manifest?.locales) ? manifest.locales : []) {
      if (!locale || locale.tag === canonical || typeof locale.path !== 'string') continue;
      const normalized = locale.path.replace(/\\/g, '/').replace(/^\.\//, '');
      const relativeToDocs = normalized.startsWith('docs/') ? normalized.slice(5) : normalized;
      const first = relativeToDocs.split('/').filter(Boolean)[0];
      if (first && !BUCKETS.includes(first)) roots.add(first);
    }
    return roots;
  } catch {
    return new Set();
  }
}

/** Heuristic bucket from a filename (fallback when no explicit map / folder). */
function heuristicBucket(name) {
  const n = name.toLowerCase();
  if (/tutorial|getting-started|quickstart|first-/.test(n)) return 'tutorials';
  if (/how-to|howto|guide|customizing|setup|install/.test(n)) return 'how-to';
  if (/format|reference|levels|api|spec|schema|config/.test(n)) return 'reference';
  if (/architecture|design|plan|concept|rationale|why|overview/.test(n)) return 'explanation';
  return null;
}

/** First `# H1` text, else the filename. */
function titleOf(text, fallback) {
  const m = text.match(/^#\s+(.+?)\s*$/m);
  return m ? m[1].trim() : fallback;
}

/** First real paragraph (skips headings, comments, quotes, lists), truncated. */
function summaryOf(text) {
  for (const raw of text.split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#') || line.startsWith('<!--') || line.startsWith('>') || line.startsWith('-') || line.startsWith('*') || line.startsWith('|') || line.startsWith('```') || line.startsWith('---') || line.startsWith('===')) continue;
    return line.length > 120 ? line.slice(0, 117) + '…' : line;
  }
  return '';
}

/** All `.md` under dir, recursively. */
function listMd(dir) {
  const out = [];
  let entries = [];
  try {
    entries = readdirSync(dir, { withFileTypes: true })
      .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  } catch {
    return out;
  }
  for (const e of entries) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...listMd(p));
    else if (e.name.endsWith('.md')) out.push(p);
  }
  return out;
}

function writeAtomic(file, content) {
  const tmp = `${file}.tmp`;
  writeFileSync(tmp, content);
  renameSync(tmp, file);
}

/** Seeds a bucket dir + its README stub (write-if-missing — never clobbers). */
function ensureBucket(docsDir, bucket) {
  const dir = join(docsDir, bucket);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const readme = join(dir, 'README.md');
  if (!existsSync(readme)) {
    const m = BUCKET_META[bucket];
    writeFileSync(readme, `# ${bucket} — ${m.tag}\n\n${m.blurb}\n\n_New ${bucket} docs go in this folder; \`/docs-reindex\` will list them in the docs index._\n`);
    return true;
  }
  return false;
}

/**
 * Reindexes `docs/` under `root`. Idempotent; never moves/deletes content.
 * @param {string} root project root
 * @returns {{ ok: boolean, indexed: number, buckets: Record<string,number>, seeded: string[], unclassified: string[], localizedRoots:string[] }}
 */
export function reindexDocs(root = process.cwd()) {
  const docsDir = resolve(root, 'docs');
  if (!existsSync(docsDir)) mkdirSync(docsDir, { recursive: true });

  let map = {};
  const mapPath = join(docsDir, '.diataxis.json');
  if (existsSync(mapPath)) {
    try {
      map = JSON.parse(readFileSync(mapPath, 'utf-8').replace(/^﻿/, '')) || {};
    } catch {
      map = {};
    }
  }

  const seeded = [];
  for (const b of BUCKETS) if (ensureBucket(docsDir, b)) seeded.push(`docs/${b}/README.md`);

  const grouped = { tutorials: [], 'how-to': [], reference: [], explanation: [] };
  const meta = [];
  const unclassified = [];
  const metaRules = metaFileRules(map);
  const localeRoots = localizedRoots(docsDir);

  for (const file of listMd(docsDir)) {
    const rel = relative(docsDir, file).replace(/\\/g, '/');
    const rootSegment = rel.split('/')[0];
    if (localeRoots.has(rootSegment)) continue;
    const base = rel.split('/').pop().toLowerCase();
    if (rel === 'README.md') continue; // the generated canonical index
    if (BUCKETS.includes(rootSegment) && base === 'readme.md') continue; // bucket stubs
    const text = readFileSync(file, 'utf-8').replace(/^﻿/, '');
    const entry = { rel, title: titleOf(text, rel), summary: summaryOf(text) };

    if (META_FILES.has(base)) {
      const explicitlyIncluded = metaRules.include.has(rel.toLowerCase());
      if (explicitlyIncluded || !metaRules.exclude.has(rel.toLowerCase())) meta.push(entry);
      continue;
    }
    const folder = rel.includes('/') ? rootSegment : null;
    const bucket = map[rel] || (BUCKETS.includes(folder) ? folder : null) || heuristicBucket(base);
    if (bucket && grouped[bucket]) grouped[bucket].push(entry);
    else unclassified.push(entry);
  }

  const indexPath = join(docsDir, 'README.md');
  let indexWritten = false;
  if (!existsSync(indexPath) || readFileSync(indexPath, 'utf-8').includes(INDEX_MARKER)) {
    writeAtomic(indexPath, renderIndex(grouped, meta, unclassified));
    indexWritten = true;
  }
  const buckets = Object.fromEntries(BUCKETS.map((b) => [b, grouped[b].length]));
  return {
    ok: true,
    indexWritten,
    indexed: Object.values(buckets).reduce((a, b) => a + b, 0),
    buckets,
    seeded,
    unclassified: unclassified.map((e) => e.rel),
    localizedRoots: [...localeRoots].sort(),
  };
}

function renderEntry(e) {
  return `- [${e.title}](${e.rel})${e.summary ? ` — ${e.summary}` : ''}`;
}

function renderIndex(grouped, meta, unclassified) {
  const lines = [
    '# Documentation',
    '',
    '<!-- AUTO-GENERATED by docs-reindex.mjs (ADR-0030). Reclassify via docs/.diataxis.json, then re-run `/docs-reindex`. Edits here are overwritten. -->',
    '',
    'Organized by [Diátaxis](https://diataxis.fr/) — by what you are trying to do.',
    '',
  ];
  for (const b of BUCKETS) {
    const m = BUCKET_META[b];
    lines.push(`## ${m.icon} ${b[0].toUpperCase() + b.slice(1)} — ${m.tag}`, `_${m.blurb}_`, '');
    if (grouped[b].length) grouped[b].forEach((e) => lines.push(renderEntry(e)));
    else if (b === 'tutorials') lines.push('_Getting started lives in the root [README](../README.md)._');
    else lines.push(`_None yet — add to \`docs/${b}/\` or map in \`docs/.diataxis.json\`._`);
    lines.push('');
  }
  if (meta.length) {
    lines.push('## 🗂️ Planning & meta', '');
    meta.forEach((e) => lines.push(renderEntry(e)));
    lines.push('');
  }
  if (unclassified.length) {
    lines.push('## ❓ Unclassified', '_Add these to `docs/.diataxis.json` so they land in a Diátaxis mode:_', '');
    unclassified.forEach((e) => lines.push(renderEntry(e)));
    lines.push('');
  }
  return lines.join('\n');
}

// CLI
if (process.argv[1]?.endsWith('docs-reindex.mjs')) {
  const report = reindexDocs(process.cwd());
  if (process.argv.includes('--json')) {
    console.log(JSON.stringify(report, null, 2));
  } else {
    console.log(`📚 docs-reindex — ${report.indexed} doc(s) indexed across ${BUCKETS.length} Diátaxis modes.`);
    for (const [b, n] of Object.entries(report.buckets)) console.log(`   ${BUCKET_META[b].icon} ${b}: ${n}`);
    if (report.localizedRoots.length) console.log(`   🌐 localized roots excluded from canonical index: ${report.localizedRoots.join(', ')}`);
    if (!report.indexWritten) console.log('   ℹ️  docs/README.md is hand-written (no marker) — left untouched.');
    if (report.seeded.length) console.log(`   seeded: ${report.seeded.join(', ')}`);
    if (report.unclassified.length) console.log(`   ⚠️  unclassified (add to docs/.diataxis.json): ${report.unclassified.join(', ')}`);
  }
}
