#!/usr/bin/env node
/**
 * Regenerates `contextkit/memory/SESSIONS.md` as an INDEX of the per-session
 * markdown files under `contextkit/memory/sessions/`.
 *
 * Why a derived index? With multiple parallel sessions, a monolithic file is
 * a merge-conflict hotspot. Each session writes its OWN file; the aggregate
 * is rebuilt from filesystem state.
 *
 * Entry naming: `<YYYY-MM-DD>-<NN>-<slug>.md`
 *   - NN: zero-padded monotonic session number.
 *   - slug: `[a-z0-9._-]` (kebab-case + version dots/underscores).
 *
 * Usage:  node contextkit/tools/scripts/session-reindex.mjs
 *         (also wired into the pre-commit git hook)
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathsFor } from '../../runtime/config/paths.mjs';

const ROOT = process.cwd();
const P = pathsFor(ROOT);
const SESSIONS_DIR = P.sessions;
const INDEX_PATH = P.sessionsIndex;
const ENTRY_PATTERN = /^(\d{4}-\d{2}-\d{2})-(\d{2,})-([a-z0-9._-]+)\.md$/;

async function extractTitle(filePath, fallbackSlug) {
  try {
    const content = await readFile(filePath, 'utf-8');
    const heading = content.split('\n').find((l) => l.startsWith('# '));
    return heading ? heading.slice(2).trim() : fallbackSlug;
  } catch {
    return fallbackSlug;
  }
}

async function listEntries() {
  let files = [];
  try {
    files = await readdir(SESSIONS_DIR);
  } catch {
    return [];
  }
  const entries = [];
  for (const filename of files) {
    const match = ENTRY_PATTERN.exec(filename);
    if (!match) continue;
    const [, date, numberStr, slug] = match;
    const title = await extractTitle(resolve(SESSIONS_DIR, filename), slug);
    entries.push({ filename, date, number: Number.parseInt(numberStr, 10), slug, title });
  }
  entries.sort((a, b) => (b.number !== a.number ? b.number - a.number : b.date.localeCompare(a.date)));
  return entries;
}

function buildIndex(entries) {
  const out = [];
  out.push('# Session History');
  out.push('');
  out.push('> ⚠️  **AUTO-GENERATED FILE — DO NOT EDIT BY HAND**.');
  out.push('> Each session lives in its own file under `contextkit/memory/sessions/`.');
  out.push('> Regenerated by `session-reindex` (also runs on pre-commit).');
  out.push('');
  out.push('Register a new session with `/log-session`.');
  out.push('');
  if (entries.length === 0) {
    out.push('_(No sessions registered yet.)_');
    out.push('');
    return out.join('\n');
  }
  out.push(`Total registered sessions: **${entries.length}** (newest first).`);
  out.push('');
  out.push('| # | Date | Title | File |');
  out.push('| --- | --- | --- | --- |');
  for (const e of entries) {
    out.push(`| ${String(e.number).padStart(2, '0')} | ${e.date} | ${e.title} | [${e.filename}](sessions/${e.filename}) |`);
  }
  out.push('');
  return out.join('\n');
}

async function main() {
  const entries = await listEntries();
  await writeFile(INDEX_PATH, buildIndex(entries), 'utf-8');
  console.log(`✅ SESSIONS.md regenerated — ${entries.length} entries indexed.`);
}

main().catch((err) => {
  console.error('❌ Failed to reindex sessions:', err);
  process.exit(1);
});
