#!/usr/bin/env node
/**
 * Aggregates active session claims into `contextkit/memory/WORKSPACE.md`.
 *
 * Each active session writes its own JSON under `.claude/.workspace/<sid>.json`
 * (gitignored local state). This scans them, drops stale entries (no heartbeat
 * for > 1h), and rebuilds the committed markdown summary.
 *
 * The summary also surfaces explicit task associations and cross-session
 * collisions. It never changes canonical task status: inactivity is a workspace
 * observation, not authorization for an automatic task transition.
 *
 * Usage:  node contextkit/tools/scripts/workspace-sync.mjs
 */
import { readdir, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathsFor } from '../../runtime/config/paths.mjs';
import { writeFileAtomic } from '../../runtime/hooks/safe-io.mjs';

const ROOT = process.cwd();
const WORKSPACE_DIR = resolve(ROOT, '.claude/.workspace');
const OUTPUT_PATH = pathsFor(ROOT).workspaceIndex;
const STALE_AFTER_MS = 60 * 60 * 1000;

async function loadClaims() {
  let files = [];
  try {
    files = await readdir(WORKSPACE_DIR);
  } catch {
    return [];
  }
  const claims = [];
  for (const filename of files) {
    if (!filename.endsWith('.json')) continue;
    try {
      claims.push(JSON.parse(await readFile(resolve(WORKSPACE_DIR, filename), 'utf-8')));
    } catch {
      /* skip malformed */
    }
  }
  return claims;
}

function isStale(claim) {
  if (typeof claim?.lastHeartbeat !== 'number') return true;
  return Date.now() - claim.lastHeartbeat > STALE_AFTER_MS;
}

function relativeTime(ms) {
  const s = Math.floor((Date.now() - ms) / 1000);
  if (s < 60) return `${s}s ago`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

function renderTasksTable(active) {
  const rows = [];
  const seen = new Map();
  for (const record of active) {
    if (!Array.isArray(record.tasks)) continue;
    for (const task of record.tasks) {
      const collision = seen.has(task.id);
      seen.set(task.id, (seen.get(task.id) || 0) + 1);
      rows.push({ id: task.id, sid: (record.sessionId ?? '?').slice(0, 8), user: record.user ?? '_unknown_', branch: record.branch ?? '_detached_', started: relativeTime(task.startedAt || Date.now()), heartbeat: relativeTime(task.lastHeartbeat || Date.now()), collision });
    }
  }
  if (rows.length === 0) return [];
  const out = [`## 🔵 Working tasks (${rows.length})`, '', '| Task | Session | User | Branch | Started | Heartbeat |', '| --- | --- | --- | --- | --- | --- |'];
  for (const r of rows) {
    const id = r.collision || (seen.get(r.id) || 0) > 1 ? `⚠️ ${r.id}` : r.id;
    out.push(`| ${id} | \`${r.sid}\` | ${r.user} | \`${r.branch}\` | ${r.started} | ${r.heartbeat} |`);
  }
  out.push('');
  return out;
}

function buildMarkdown(active, stale) {
  const out = [];
  out.push('# Workspace — Active Sessions');
  out.push('');
  out.push('> ⚠️  **AUTO-GENERATED FILE — DO NOT EDIT BY HAND**.');
  out.push('> Regenerated by `workspace-sync` (runs on pre-commit) from');
  out.push('> `.claude/.workspace/<sid>.json` files maintained by hooks and slash commands.');
  out.push('');
  const tasksSection = renderTasksTable(active);
  if (active.length === 0 && stale.length === 0 && tasksSection.length === 0) {
    out.push('_(No active sessions. The workspace is idle.)_');
    out.push('');
    return out.join('\n');
  }
  out.push(...tasksSection);
  if (active.length > 0) {
    out.push(`## 🟢 Active sessions (${active.length})`);
    out.push('');
    out.push('| Session | User | Branch | Started | Last activity | Claims |');
    out.push('| --- | --- | --- | --- | --- | --- |');
    for (const c of active) {
      const sid = (c.sessionId ?? '?').slice(0, 8);
      const claims = Array.isArray(c.claims) && c.claims.length > 0 ? c.claims.map((cl) => `\`${cl.path}\``).join(', ') : '_(none)_';
      out.push(`| \`${sid}\` | ${c.user ?? '_unknown_'} | \`${c.branch ?? '_detached_'}\` | ${c.startedAt ? relativeTime(c.startedAt) : '?'} | ${c.lastHeartbeat ? relativeTime(c.lastHeartbeat) : '?'} | ${claims} |`);
    }
    out.push('');
  }
  if (stale.length > 0) {
    out.push(`## 🟡 Stale (${stale.length}) — no heartbeat for > 1h`);
    out.push('');
    out.push('| Session | User | Branch | Last activity |');
    out.push('| --- | --- | --- | --- |');
    for (const c of stale) {
      out.push(`| \`${(c.sessionId ?? '?').slice(0, 8)}\` | ${c.user ?? '_unknown_'} | \`${c.branch ?? '_detached_'}\` | ${c.lastHeartbeat ? relativeTime(c.lastHeartbeat) : '?'} |`);
    }
    out.push('');
  }
  out.push('---');
  out.push('');
  out.push('Slash commands: `/claim <path>` to reserve a path · `/pipeline start <id>` to attach a task · `/release` / `/pipeline stop <id>` to free · `/worktree-new <feature>` for parallel work.');
  return out.join('\n');
}

async function main() {
  const claims = await loadClaims();
  const active = claims.filter((c) => !isStale(c));
  const stale = claims.filter(isStale);
  await writeFileAtomic(OUTPUT_PATH, buildMarkdown(active, stale));
  console.log(`✅ WORKSPACE.md regenerated — ${active.length} active, ${stale.length} stale.`);
}

main().catch((err) => {
  console.error('❌ Failed to sync workspace:', err);
  process.exit(1);
});
