/**
 * MCP-006 resource definitions and read handlers.
 *
 * Resources expose ContextDevKit artifacts as URI-addressed blobs.
 * All reads are best-effort; missing artifacts yield a "not yet generated"
 * message rather than an error — constitution §8 (graceful degradation).
 *
 * URI scheme:  contextdevkit://project/<artifact>
 *
 * [MCP-006, ADR-0073]
 */
import { readFile, readdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathsFor } from '../runtime/config/paths.mjs';
import { parseAdr, renderCatalogLine, ADR_FILENAME_RE } from '../tools/scripts/adr-digest-core.mjs';

const ROOT = process.cwd();
const P = pathsFor(ROOT);

const readSafe = (abs) => readFile(abs, 'utf-8').catch(() => null);

// ─── Resource catalog ────────────────────────────────────────────────────────

/**
 * The static list of resources this server exposes. Consumed by the
 * resources/list handler in server.mjs.
 */
export const RESOURCE_LIST = [
  {
    uri: 'contextdevkit://project/map',
    name: 'Project Map',
    description: 'Structural map of the project (modules, deps, insights). Generated by /project-map.',
    mimeType: 'application/json',
  },
  {
    uri: 'contextdevkit://workflow/current',
    name: 'Current Workflow Status',
    description: 'All active workflows and their phases.',
    mimeType: 'application/json',
  },
  {
    uri: 'contextdevkit://pipeline/working',
    name: 'Pipeline Working Cards',
    description: 'Tasks currently in the working stage of the DevPipeline.',
    mimeType: 'application/json',
  },
  {
    uri: 'contextdevkit://memory/latest-session',
    name: 'Latest Session Log',
    description: 'The most recently registered work session.',
    mimeType: 'text/markdown',
  },
  {
    uri: 'contextdevkit://decisions/catalog',
    name: 'Decisions Catalog',
    description: 'Catalog of all Architecture Decision Records (ADRs).',
    mimeType: 'application/json',
  },
  {
    uri: 'contextdevkit://business-rules',
    name: 'Business Rules',
    description: 'Business rules and constraints from memory/business-rules/.',
    mimeType: 'text/markdown',
  },
];

// ─── Resource readers ────────────────────────────────────────────────────────

async function readProjectMap() {
  const text = await readSafe(resolve(P.projectMap, 'manifest.json'));
  if (!text) return JSON.stringify({ error: 'No project map. Run /project-map to generate one.' });
  return text;
}

async function readCurrentWorkflows() {
  const workflowsDir = resolve(P.memory, 'workflows');
  let entries = [];
  try { entries = await readdir(workflowsDir); } catch {
    return JSON.stringify({ workflows: [], note: 'No workflows directory found.' });
  }
  const workflows = [];
  for (const entry of entries) {
    const indexPath = resolve(workflowsDir, entry, 'index.md');
    const text = await readSafe(indexPath);
    if (!text) continue;
    const fm = {};
    const fmMatch = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (fmMatch) {
      for (const line of fmMatch[1].split(/\r?\n/)) {
        const colon = line.indexOf(':');
        if (colon > 0) fm[line.slice(0, colon).trim()] = line.slice(colon + 1).trim();
      }
    }
    const phase = fm.currentPhase || '';
    if (phase && phase !== 'conclusion') {
      workflows.push({ slug: fm.slug || entry, kind: fm.kind || '', number: fm.number || '', currentPhase: phase });
    }
  }
  return JSON.stringify({ workflows, total: workflows.length });
}

async function readPipelineWorking() {
  // Import lazily to avoid circular deps in test harness
  const { listTasks } = await import('../tools/scripts/pipeline-tasks.mjs'); // dynamic to avoid circular deps in test harness
  try {
    const tasks = listTasks(P.pipeline).filter((t) => t.stage === 'working');
    return JSON.stringify({ tasks, total: tasks.length });
  } catch (err) {
    return JSON.stringify({ tasks: [], error: String(err.message) });
  }
}

async function readLatestSession() {
  const ENTRY_RE = /^(\d{4}-\d{2}-\d{2})-(\d{2,})-([a-z0-9._-]+)\.md$/;
  let files = [];
  try { files = await readdir(P.sessions); } catch { return '_No session logs found._'; }
  const entries = files
    .map((f) => ENTRY_RE.exec(f))
    .filter(Boolean)
    .map((m) => ({ filename: m[0], num: Number.parseInt(m[2], 10), date: m[1] }))
    .sort((a, b) => b.num - a.num || b.date.localeCompare(a.date));
  if (!entries.length) return '_No session logs found._';
  const text = await readSafe(resolve(P.sessions, entries[0].filename));
  return text ?? '_Session file could not be read._';
}

async function readDecisionsCatalog() {
  let files = [];
  try { files = await readdir(P.decisions); } catch {
    return JSON.stringify({ decisions: [], note: 'No decisions directory found.' });
  }
  const sorted = files
    .filter((f) => ADR_FILENAME_RE.test(f) && f !== '_TEMPLATE.md')
    .sort()
    .reverse();
  const decisions = [];
  for (const name of sorted) {
    const text = await readSafe(resolve(P.decisions, name));
    if (text !== null) {
      const record = parseAdr(text, name);
      decisions.push({ ...record, file: name, line: renderCatalogLine(record) });
    }
  }
  return JSON.stringify({ decisions, total: decisions.length });
}

async function readBusinessRules() {
  let files = [];
  try { files = await readdir(P.businessRules); } catch { return '_No business-rules directory found._'; }
  const mdFiles = files.filter((f) => f.endsWith('.md')).sort();
  if (!mdFiles.length) return '_No business rules defined yet._';
  const parts = [];
  for (const name of mdFiles) {
    const text = await readSafe(resolve(P.businessRules, name));
    if (text) parts.push(`## ${name}\n\n${text}`);
  }
  return parts.join('\n\n---\n\n');
}

// ─── Dispatch table ──────────────────────────────────────────────────────────

const READERS = {
  'contextdevkit://project/map': readProjectMap,
  'contextdevkit://workflow/current': readCurrentWorkflows,
  'contextdevkit://pipeline/working': readPipelineWorking,
  'contextdevkit://memory/latest-session': readLatestSession,
  'contextdevkit://decisions/catalog': readDecisionsCatalog,
  'contextdevkit://business-rules': readBusinessRules,
};

/**
 * Reads the contents of a resource by URI.
 * @param {string} uri
 * @returns {Promise<{contents: [{uri: string, mimeType: string, text: string}]}>}
 */
export async function readResource(uri) {
  const reader = READERS[uri];
  if (!reader) {
    return {
      contents: [{
        uri,
        mimeType: 'text/plain',
        text: `Unknown resource URI: ${uri}`,
      }],
    };
  }
  const text = await reader();
  const meta = RESOURCE_LIST.find((r) => r.uri === uri);
  return {
    contents: [{
      uri,
      mimeType: meta?.mimeType ?? 'text/plain',
      text,
    }],
  };
}
