/**
 * Canonical usage event schema + normalization (EACP-01, ADR-0078).
 *
 * WHY a separate schema module: every downstream consumer (attribution lenses,
 * adapters, cost-projection, budget gate) must agree on the same field names
 * and normalization contract. A shared schema prevents the "summing
 * cumulative totals as if they were deltas" bug.
 *
 * Key invariant (validated by bucketsClose in usage-buckets.mjs):
 *   total === freshInput + output + cacheRead + cacheWrite + reasoning
 *
 * IMPORTANT TERMINOLOGY: bucket sums are TOKEN THROUGHPUT, not cost/spend.
 * Pricing requires a model-rate table that is outside this module's
 * responsibility (ADR-0079 Phase 2). Nothing here auto-labels a sum as spend.
 *
 * Zero runtime dependencies — plain Node.js ESM, node:* only.
 */

import { throughput } from './usage-buckets.mjs';

// ---------------------------------------------------------------------------
// Schema version
// ---------------------------------------------------------------------------

/** Monotonic schema identifier — bump when the shape changes in a breaking way. */
export const SCHEMA_VERSION = 'eacp-usage-event/1';

// ---------------------------------------------------------------------------
// Typedef (documentation only — JS has no compile-time types)
// ---------------------------------------------------------------------------

/**
 * @typedef {Object} UsageBuckets
 * @property {number} freshInput  - Input tokens NOT served from cache
 * @property {number} output      - Output tokens generated by the model
 * @property {number} cacheRead   - Input tokens served from the prompt cache
 * @property {number} cacheWrite  - Tokens written to the prompt cache
 * @property {number} reasoning   - Extended-thinking / reasoning tokens
 */

/**
 * @typedef {'delta'|'cumulative'} BucketMode
 * Cumulative events carry running totals since session start; delta events
 * carry per-step increments. Most adapters emit deltas (Claude transcripts).
 * Always normalize to delta before aggregating — see `toDelta`.
 */

/**
 * @typedef {'direct'|'derived'|'inferred'|'unknown'} ConfidenceTier
 * Expresses how trustworthy the bucket values are:
 *   direct   — read from the authoritative host API with no transformation
 *   derived  — computed from direct signals (e.g. delta from cumulative)
 *   inferred — estimated from heuristics or incomplete signal
 *   unknown  — provenance unclear; treat as a lower bound
 */

/**
 * @typedef {Object} UsageEvent
 * The canonical token-usage record the EACP platform routes through.
 *
 * @property {string}          schemaVersion    - Always SCHEMA_VERSION
 * @property {string}          host             - Tool host ('claude-code', 'cursor', …)
 * @property {string}          [provider]       - LLM provider ('anthropic', …)
 * @property {string}          sessionId        - Stable session identifier
 * @property {string}          [runId]          - Finer-grained run within session
 * @property {string}          [taskId]         - Pipeline card / task reference
 * @property {string}          [phase]          - Workflow phase label
 * @property {string}          modelRequested   - Model id requested by the user
 * @property {string}          modelEffective   - Model id that actually responded
 * @property {boolean}         fallbackUsed     - True if effective ≠ requested
 * @property {'main'|'subagent'} agentScope     - Main loop or fanned-out subagent
 * @property {string}          [attributionSkill] - Slash command that owns this turn
 * @property {UsageBuckets}    buckets          - Token counts per category
 * @property {BucketMode}      bucketMode       - 'delta' or 'cumulative'
 * @property {number}          total            - Sum of all bucket values
 * @property {number}          ts               - Unix ms timestamp
 * @property {ConfidenceTier}  confidence       - Trustworthiness of the values
 * @property {Object}          source           - Provenance metadata
 * @property {string}          source.adapter   - Adapter id that produced this event
 * @property {string}          [source.raw_ref] - Reference to the raw transcript line
 */


// ---------------------------------------------------------------------------
// Validation constants
// ---------------------------------------------------------------------------

const BUCKET_KEYS = ['freshInput', 'output', 'cacheRead', 'cacheWrite', 'reasoning'];
const VALID_BUCKET_MODES = new Set(['delta', 'cumulative']);
const VALID_CONFIDENCES = new Set(['direct', 'derived', 'inferred', 'unknown']);
const REQUIRED_FIELDS = ['host', 'sessionId', 'bucketMode', 'buckets'];

// ---------------------------------------------------------------------------
// Normalization
// ---------------------------------------------------------------------------

/**
 * Accepts a raw (potentially incomplete) usage event object and returns a
 * fully-formed canonical UsageEvent.
 *
 * Validation is fail-fast: the first violated constraint throws immediately
 * so no downstream consumer receives a partially-formed record.
 *
 * Defaults applied:
 *   - schemaVersion → SCHEMA_VERSION
 *   - confidence    → 'unknown' when absent
 *   - total         → throughput(buckets)
 *   - ts            → Date.now() when absent
 *   - modelRequested/modelEffective → 'unknown' when absent
 *   - fallbackUsed  → false when absent
 *   - agentScope    → 'main' when absent
 *
 * @param {object} raw - Untrusted event object from an adapter
 * @returns {UsageEvent}
 * @throws {TypeError}  when a required field is missing or has the wrong type
 * @throws {RangeError} when a value is out of the allowed set or is negative
 */
export function normalizeEvent(raw) {
  if (!raw || typeof raw !== 'object') {
    throw new TypeError('normalizeEvent: raw event must be a non-null object');
  }

  // Required field presence check
  for (const field of REQUIRED_FIELDS) {
    if (raw[field] === undefined || raw[field] === null) {
      throw new TypeError(`normalizeEvent: required field '${field}' is missing`);
    }
  }

  if (typeof raw.host !== 'string' || !raw.host.trim()) {
    throw new TypeError("normalizeEvent: 'host' must be a non-empty string");
  }

  if (typeof raw.sessionId !== 'string' || !raw.sessionId.trim()) {
    throw new TypeError("normalizeEvent: 'sessionId' must be a non-empty string");
  }

  if (!VALID_BUCKET_MODES.has(raw.bucketMode)) {
    throw new RangeError(
      `normalizeEvent: 'bucketMode' must be 'delta' or 'cumulative', got '${raw.bucketMode}'`
    );
  }

  // Confidence — default to 'unknown' rather than throwing on absent field
  const confidence = raw.confidence !== undefined ? raw.confidence : 'unknown';
  if (!VALID_CONFIDENCES.has(confidence)) {
    throw new RangeError(
      `normalizeEvent: 'confidence' must be one of [direct, derived, inferred, unknown], got '${confidence}'`
    );
  }

  // Buckets — validate every key is a non-negative finite number
  const rawBuckets = raw.buckets;
  if (typeof rawBuckets !== 'object' || rawBuckets === null) {
    throw new TypeError("normalizeEvent: 'buckets' must be an object");
  }
  const normalizedBuckets = { freshInput: 0, output: 0, cacheRead: 0, cacheWrite: 0, reasoning: 0 };
  for (const key of BUCKET_KEYS) {
    const v = rawBuckets[key] !== undefined ? rawBuckets[key] : 0;
    if (typeof v !== 'number' || !isFinite(v)) {
      throw new TypeError(`normalizeEvent: buckets.${key} must be a finite number, got ${v}`);
    }
    if (v < 0) {
      throw new RangeError(`normalizeEvent: buckets.${key} must be ≥ 0, got ${v}`);
    }
    normalizedBuckets[key] = v;
  }

  const total = throughput(normalizedBuckets);

  return {
    schemaVersion:    SCHEMA_VERSION,
    host:             raw.host,
    provider:         raw.provider !== undefined ? raw.provider : undefined,
    sessionId:        raw.sessionId,
    runId:            raw.runId,
    taskId:           raw.taskId,
    phase:            raw.phase,
    modelRequested:   typeof raw.modelRequested === 'string' ? raw.modelRequested : 'unknown',
    modelEffective:   typeof raw.modelEffective === 'string' ? raw.modelEffective : 'unknown',
    fallbackUsed:     typeof raw.fallbackUsed === 'boolean' ? raw.fallbackUsed : false,
    agentScope:       raw.agentScope === 'subagent' ? 'subagent' : 'main',
    attributionSkill: raw.attributionSkill,
    buckets:          normalizedBuckets,
    bucketMode:       raw.bucketMode,
    total,
    ts:               typeof raw.ts === 'number' ? raw.ts : Date.now(),
    confidence,
    source:           raw.source && typeof raw.source === 'object'
                        ? raw.source
                        : { adapter: 'unknown' },
  };
}
