/**
 * render-grok.mjs - MCP config renderer for the Grok Build host.
 *
 * Produces one project-scoped `.grok/config.toml` artifact. Grok's project
 * configuration uses `[mcp_servers.<id>]` tables and `${ENV_NAME}` references;
 * the shared resolver intentionally uses the Claude/Codex `${env:ENV_NAME}`
 * shape, so this renderer translates references at the host boundary without
 * ever materialising a secret value.
 *
 * CONTRACT:
 *   - renderHost(manifest, registry) is PURE: no I/O.
 *   - Secrets appear only as Grok environment references.
 *   - Only servers allowed for `grok` or `*` are emitted.
 *   - Project scope is the only supported scope because Grok reads `.grok/`.
 *
 * @module render/render-grok
 */

import { filterForHost } from './render-shared.mjs';
import { PLATFORM_DIR } from '../../config/paths.mjs';

/** Canonical host id for this renderer. */
export const HOST_ID = 'grok';

/** @typedef {import('./render-shared.mjs').RegistryEntry} RegistryEntry */
/** @typedef {import('./render-shared.mjs').ConfigArtifact} ConfigArtifact */
/** @typedef {import('./render-shared.mjs').ResolvedRenderEntry} ResolvedRenderEntry */

/** Registry id for the ContextDevKit-owned native MCP server. */
const CONTEXTDEVKIT_SERVER_ID = 'contextdevkit';

/**
 * Escapes a value for a TOML basic string.
 *
 * @param {string} value
 * @returns {string}
 */
function tomlString(value) {
  return `"${String(value)
    .replaceAll('\\', '\\\\')
    .replaceAll('"', '\\"')
    .replaceAll('\b', '\\b')
    .replaceAll('\f', '\\f')
    .replaceAll('\n', '\\n')
    .replaceAll('\r', '\\r')
    .replaceAll('\t', '\\t')}"`;
}

/**
 * Converts a shared env reference into Grok's `${NAME}` syntax.
 *
 * @param {string} value shared `${env:NAME}` reference
 * @param {string} serverId server id for error context
 * @returns {string}
 * @throws {TypeError} when the shared reference is malformed
 */
function toGrokEnvReference(value, serverId) {
  const match = /^\$\{env:([A-Z][A-Z0-9_]*)\}$/.exec(value);
  if (!match) {
    throw new TypeError(`render-grok: server '${serverId}' has an invalid environment reference`);
  }
  return `\$\{${match[1]}\}`;
}

/**
 * Serialises environment references as a TOML inline table.
 *
 * @param {ResolvedRenderEntry} server
 * @returns {string}
 */
function envToToml(server) {
  const entries = Object.entries(server.env).map(([name, value]) =>
    `${name} = ${tomlString(toGrokEnvReference(value, server.id))}`
  );
  return entries.length > 0 ? `env = { ${entries.join(', ')} }` : '';
}

/**
 * Uses the installed native ContextDevKit MCP server instead of requiring a
 * separately published package when the canonical server is selected.
 *
 * @param {ResolvedRenderEntry} server
 * @returns {ResolvedRenderEntry}
 */
function useNativeContextDevKitServer(server) {
  if (server.id !== CONTEXTDEVKIT_SERVER_ID || server.transport !== 'stdio') return server;
  return {
    ...server,
    command: 'node',
    args: [`${PLATFORM_DIR}/mcp-server/server.mjs`],
  };
}

/**
 * Serialises one resolved server to a Grok MCP table.
 *
 * @param {ResolvedRenderEntry} server
 * @returns {string}
 */
function serverToToml(server) {
  const lines = [`[mcp_servers.${tomlString(server.id)}]`];
  if (server.transport === 'streamable-http') {
    lines.push(`url = ${tomlString(server.url)}`);
  } else {
    lines.push(`command = ${tomlString(server.command)}`);
    lines.push(`args = [${server.args.map(tomlString).join(', ')}]`);
  }
  const envLine = envToToml(server);
  if (envLine) lines.push(envLine);
  return lines.join('\n');
}

/**
 * Builds a Grok project config body.
 *
 * @param {ResolvedRenderEntry[]} entries
 * @returns {string}
 */
function buildTomlBody(entries) {
  if (entries.length === 0) return '# No MCP servers enabled for Grok.\n';
  return '# Generated by ContextDevKit from contextkit/mcp/project-manifest.json.\n' +
    entries.map(serverToToml).join('\n\n') + '\n';
}

/**
 * Renders the Grok project MCP configuration.
 *
 * @param {Object} manifest parsed project manifest
 * @param {RegistryEntry[]} registry loaded registry entries
 * @param {{scopes?: string[]}} [options]
 * @returns {ConfigArtifact[]}
 * @throws {TypeError} when manifest or registry is structurally invalid
 */
export function renderHost(manifest, registry, options = {}) {
  if (!manifest || !Array.isArray(manifest.servers)) {
    throw new TypeError('render-grok: manifest must have a servers array');
  }
  if (!Array.isArray(registry)) {
    throw new TypeError('render-grok: registry must be an array');
  }

  const scopes = options.scopes ?? ['project'];
  if (!scopes.includes('project')) return [];

  const { entries: resolvedEntries, skipped } = filterForHost(manifest.servers, registry, HOST_ID);
  const entries = resolvedEntries.map(useNativeContextDevKitServer);
  return [{
    filePath: '.grok/config.toml',
    format: 'toml',
    content: buildTomlBody(entries),
    servers: entries,
    skipped,
    host: HOST_ID,
    scope: 'project',
  }];
}
